Color tests

diff --git a/php/mako-framework/post-receive b/php/mako-framework/post-receive
--- a/php/mako-framework/post-receive
+++ b/php/mako-framework/post-receive
@@ -2,16 +2,35 @@
 #
 # An example hook script for the "post-receive" event.
 
+## App name
 APP="Gift - API"
+
+# App root.
 APP_ROOT=/srv/www/gift/api
+
+# App environment
 ENV='production'
 
-echo "*************"
-echo "Deploying $APP"
-echo "*************"
+# Colors
 
-cd $APP_ROOT || echo "Missing app root."
+# Black        0;30     Dark Gray     1;30
+# Blue         0;34     Light Blue    1;34
+# Green        0;32     Light Green   1;32
+# Cyan         0;36     Light Cyan    1;36
+# Red          0;31     Light Red     1;31
+# Purple       0;35     Light Purple  1;35
+# Brown/Orange 0;33     Yellow        1;33
+# Light Gray   0;37     White         1;37
 
+red='\e[0;31m';
+light_green='\e[1;32m';
+no_color='\e[0m';
+
+echo -e "${light_green}*************${no_color}"
+echo -e "${light_green}Deploying $APP ${no_color}"
+echo -e "${light_green}************* ${no_color}"
+
+cd $APP_ROOT || echo "${red}Missing app root. ${no_color}"
 
 echo "*************"
 echo "Pull updates from remote."
@@ -37,6 +56,6 @@ echo "************"
 
 php reactor migrate.status --env=$ENV
 
-echo "**************"
-echo "Deploy end."
-echo "**************"
+echo -e "${light_green}************** ${no_color}"
+echo -e "${light_green}Deploy end. ${no_color}"
+echo -e "{$light_green}************** ${no_color}"
